## Get set of startups with M&A

### This notebook provides the code to get the set of startups acquired via M&A
### Notes:
- aaaa
### Logs: 
Aug 15:
- Notebook created
-

## Download deals data from BQ

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker
from google.cloud import bigquery
import os

# Define project on BQ
project_id = "sci-tech-data"

# Authenticate to Google Cloud
client = bigquery.Client(project=project_id)

# Set allow_large_results to True
job_config = bigquery.QueryJobConfig()
job_config.allow_large_results = True

pd.set_option('display.max_columns', None)

os.chdir('/home/jupyter')
!pwd
# # %cd 
# !pwd

%connect_info
# (base) jupyter@starfire-1:~$ pip install jupyter-console
# (base) jupyter@starfire-1:~$ !jupyter console --existing

/home/jupyter
{
  "shell_port": 57351,
  "iopub_port": 49057,
  "stdin_port": 56405,
  "control_port": 57461,
  "hb_port": 42485,
  "ip": "127.0.0.1",
  "key": "b86ff8be-2d21e231b2bcfd9007876563",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "conda-root-py",
  "jupyter_session": "/home/jupyter/starfire/notebooks/01_motivation.ipynb"
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-1946a5de-85eb-4f1a-8f31-e891233350ec.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.

In [6]:
# Download deals

# Download data from BQ
print('downloading pitchbook deals... \n')

# Construct the SQL query to fetch data from BigQuery
query = f'''
SELECT
    *
FROM `starfire-410116.derived.pb_all_deals`
'''

# Fetch data from BigQuery
query_job = client.query(query, job_config=job_config)
results = query_job.result()  # Waits for the query to complete

# Convert the result to a pandas DataFrame
sup = results.to_dataframe()

# Print the first few rows of the DataFrame
print('All deals:')
print(f'shape: {sup.shape}')
sup.head(4)

downloading pitchbook deals...

All deals:
shape: (2346296, 23)

,companyid,companyname,dealid,dealdate,announceddate,dealsize,dealstatus,dealsizestatus,percentacquired,raisedtodate,vcround,totalinvestedcapital,investorownership,dealtype,dealtype2,dealtype3,dealclass,dealsynopsis,nativecurrencyofdeal,totalinvestedequity,financingstatus,newinvestors,source_tab
0,170925-58,Starts Corporation,233531-47T,1989-05-30 00:00:00+00:00,NaT,NaN,Completed,None,NaN,NaN,None,NaN,NaN,IPO,None,None,Public Investment,The company completed its initial public offer...,Japanese Yen (JPY),NaN,Corporation,NaN,ot
1,93649-15,Sinopec Canada,53649-37T,2010-05-12 00:00:00+00:00,NaT,NaN,Completed,None,NaN,NaN,None,NaN,NaN,IPO,None,None,Public Investment,The company raised an undisclosed amount of fu...,Canadian Dollars (CAD),NaN,Corporation,NaN,ot
2,124530-85,Virgin Australia Regional Airlines,69559-12T,2005-11-30 00:00:00+00:00,NaT,NaN,Completed,None,NaN,NaN,None,NaN,NaN,IPO,None,None,Public Investment,The company completed its initial public offer...,British Pounds (GBP),NaN,Corporation,NaN,ot
3,164909-71,Korea Alcohol Industrial Company,256166-38T,1992-07-28 00:00:00+00:00,NaT,NaN,Completed,None,NaN,NaN,None,NaN,NaN,IPO,None,None,Public Investment,The company completed its initial public offer...,South-Korean Won (KRW),NaN,Corporation,NaN,ot